### PR TITLE
Add keyvalue flag that will preserve string escaping

### PR DESCRIPTION
**Pull request by cristinaleonr**
This PR adds a new KeyValue flag that allows input strings to escape special characters. This way, input values can contain commas that will not be split incorrectly (e.g., a=b\,c\=d will be interpreted as key=`a` and value=`b\,c\=d`).

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/go/176)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/go/176)* status: 0 of 1 LGTMs obtained

___
*[`flagx/keyvalue_escaped.go` line 8 at r1](https://reviewable.io/reviews/m-lab/go/176#-NkLm5wa-zgpf1dpCvJO:-NkLm5wa-zgpf1dpCvJP:b-hnodwe) ([raw file](https://github.com/m-lab/go/blob/e91f7e0dfb131725fad904e08335f0027df66922/flagx/keyvalue_escaped.go#L8)):*
> ```Go
> )
> 
> // KeyValueEscaped parses "key=value" pairs from a given argument. The KeyValue flag is
> ```

nit: does `KeyValue` here mean to refer to `KeyValueEscaped`?

Or maybe I suggest slight rephrasing to emphasize the main point, from the second sentence, which might be:

```
... Unlike the KeyValue flag which is designed for repeatable arguments separated by an unescaped ',', KeyValueEscaped allows for key/value with escaped characters (i.e. `/` and `,`). ...
```

Do I understand correctly, that this only applies to `/` and `,` characters? or can any value be escaped?
___
*[`flagx/keyvalue_escaped.go` line 23 at r1](https://reviewable.io/reviews/m-lab/go/176#-NkLmTqW0LLOqoTnI1N4:-NkLmTqW0LLOqoTnI1N5:bm2n2jq) ([raw file](https://github.com/m-lab/go/blob/e91f7e0dfb131725fad904e08335f0027df66922/flagx/keyvalue_escaped.go#L23)):*
> ```Go
> // Set reads the file content for the key value.
> func (kve *KeyValueEscaped) Set(kvs string) error {
> 	reg := regexp.MustCompile(".*?[^\\\\](,|$)")
> ```

I find this difficult to parse in my head; would you be willing to write in english what this regex is meant to match?

**Comment by stephen-soltesz** [comment]
Please consider updating .travis.yml while you're here.

**Review by cristinaleonr — COMMENTED** [review]
Done!

> *[Reviewable](https://reviewable.io/reviews/m-lab/go/176#-:-NkMjGgd0ChprTDh1X0X:b-896fja)* status: 0 of 1 LGTMs obtained

___
*[`flagx/keyvalue_escaped.go` line 8 at r1](https://reviewable.io/reviews/m-lab/go/176#-NkLm5wa-zgpf1dpCvJO:-NkMipLE8sXAid67am_m:b-e59kgg) ([raw file](https://github.com/m-lab/go/blob/f745cf66b7c3494b225c57efb077bfac2b5d380e/flagx/keyvalue_escaped.go#L8)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: does `KeyValue` here mean to refer to `KeyValueEscaped`?

Or maybe I suggest slight rephrasing to emphasize the main point, from the second sentence, which might be:

```
... Unlike the KeyValue flag which is designed for repeatable arguments separated by an unescaped ',', KeyValueEscaped allows for key/value with escaped characters (i.e. `/` and `,`). ...
```

Do I understand correctly, that this only applies to `/` and `,` characters? or can any value be escaped?
</blockquote></details>

It only applies to `,` characters, since that is the key-value pair separator. I have rephrased. Let me know if that's more clear.
___
*[`flagx/keyvalue_escaped.go` line 23 at r1](https://reviewable.io/reviews/m-lab/go/176#-NkLmTqW0LLOqoTnI1N4:-NkMilewELLh-A0Kx1DC:b-sbf2jn) ([raw file](https://github.com/m-lab/go/blob/f745cf66b7c3494b225c57efb077bfac2b5d380e/flagx/keyvalue_escaped.go#L23)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I find this difficult to parse in my head; would you be willing to write in english what this regex is meant to match?
</blockquote></details>

I added a comment!

**Review by stephen-soltesz — APPROVED** [review]
Thank you. The functionality here starts to feels complex. I understand the intended use case in Locate but I'm just flagging this in case there's a need to tweak this further, it may be preferable to have Locate read in a config file directly for the complexity of the kind of input we want to provide (i.e. user agent strings and cron specs, both a little complex by themselves.)

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/go/176#-:-NkMnfho0fNWRi53G4QU:b-jqkpim)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[`flagx/keyvalue_escaped_test.go` line 147 at r4](https://reviewable.io/reviews/m-lab/go/176#-NkMm3Qh13ohnkUTwJNB:-NkMm3Qh13ohnkUTwJNC:b-h3bw2g) ([raw file](https://github.com/m-lab/go/blob/65b0101697dc1584d44ab2c34da92d176ad41ba8/flagx/keyvalue_escaped_test.go#L147)):*
> ```Go
> 
> 			// String returns the same fields given. Parse b/c order is not guaranteed.
> 			strFields := strings.Split(kve.String(), ",")
> ```

Originally this block was trying to make sure that the `String()` method generated syntax that was equivalent to the input. (i.e. so the input to a flag and the console log of the flag value were interchangeable).

I suggest eliminating this last block for this flag type, since it looks like it's doing a naive split on the comma, so the comparisons may be a pseudo check, right?

**Pull request merged**
