### PR TITLE
Implement Query.Run

### PR DESCRIPTION
**Pull request by guerremdq**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/go/174)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
@guerremdq -- the travis build failed due to new incompatibilities in the environment, please rebase to include https://github.com/m-lab/go/pull/175 which should address this issue in the environment.

**Review by stephen-soltesz — COMMENTED** [review]
@guerremdq -- for some reason the travis build did not trigger automatically after your merge, and I don't seem to be able to trigger it manually through the UI. The change lgtm, but I would feel better with a passing build as well. I've suggested a small change that could do that.

> *[Reviewable](https://reviewable.io/reviews/m-lab/go/174#-:-Ni_JvQ-15wUNsfbAVo7:b6oa6jr)* status: 0 of 1 LGTMs obtained

___
*[`cloudtest/bqfake/bqfake.go` line 236 at r1](https://reviewable.io/reviews/m-lab/go/174#-Ni_JPF47ZfPxGMdM4QL:-Ni_JPF47ZfPxGMdM4QM:b-kfcwqz) ([raw file](https://github.com/m-lab/go/blob/b2500fab6b316b78182484a6bff7ed2d90d247aa/cloudtest/bqfake/bqfake.go#L236)):*
> ```Go
> 	status *bigquery.JobStatus
> 	config QueryConfig
> 	err    error
> ```

Since we're introducing `QueryConfig` for the `ReadErr`, please rename `Job.err` to `Job.waitErr`. (This is a small request to attempt to trigger the travis build)

**Comment by guerremdq** [comment]
@stephen-soltesz Looks like the Build in Travis is not triggered , right ?

**Comment by stephen-soltesz** [comment]
Yes, I see that too -- I've opened a support ticket with Travis to see if this is a known issue or some recent change. I'll give them another day, if it's no resolved on their end I'll test this change myself. Sorry for the delay.

**Comment by stephen-soltesz** [comment]
```
$ go test -cover=1 .
ok  	github.com/m-lab/go/cloudtest/bqfake	0.135s	coverage: 100.0% of statements
```

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/go/174#-:-NigNLC_DcObFbGggN7s:bnfp4nl)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
