### PR TITLE
Add KeyArrayValue to flagx

### PR DESCRIPTION
**Pull request by cristinaleonr**
Add a new key-value flag where the value is an array of strings.

Sample usage: `-services=ndt/ndt7=ws://ndt/v7/upload,ws://ndt/v7/download`.

This change is [Reviewable](https://reviewable.io/reviews/m-lab/go/145)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
I like this idea!

> *[Reviewable](https://reviewable.io/reviews/m-lab/go/145#-:-N49JAVfANRzn3JQdVjA:bu3hzat)* status: 0 of 1 LGTMs obtained

___
*[`flagx/keyarrayvalue.go` line 8 at r2](https://reviewable.io/reviews/m-lab/go/145#-N49Ghms4BASU2vCwL73:-N49Ghms4BASU2vCwL74:basx0rp) ([raw file](https://github.com/m-lab/go/blob/11823785b2027dedb5860fee96510be6f62f9ae9/flagx/keyarrayvalue.go#L8)):*
> ```Go
> )
> 
> // KeyArrayValue maps a key to one or multiple values.
> ```

All current `*Array` types use "Array" as a suffix. https://pkg.go.dev/github.com/m-lab/go@v0.1.47/flagx

Please rename to `KeyValueArray` -- this will also sort the types naturally together with `KeyValue`. 
___
*[`flagx/keyarrayvalue.go` line 28 at r2](https://reviewable.io/reviews/m-lab/go/145#-N49HCVS2oEbZ3jiFy7F:-N49HCVS2oEbZ3jiFy7G:bv9hjus) ([raw file](https://github.com/m-lab/go/blob/11823785b2027dedb5860fee96510be6f62f9ae9/flagx/keyarrayvalue.go#L28)):*
> ```Go
> 		kav.pairs = make(map[string][]string)
> 	}
> 	v := strings.Split(p[1], ",")
> ```

Hmm...

The other *Array types use append semantics, and allow repeated flags that append the new values to the existing array...

I think this behavior can be preserved here using go's `append`.

These semantics would also mean that we could split `-service=` declarations over multiple lines for clarity, e.g.:

```
-services=ndt/ndt7=ws://ndt/v7/upload,ws://ndt/v7/download \
-services=ndt/ndt7=wss://ndt/v7/upload,wss://ndt/v7/download \
-services=ndt/ndt5=ws://ndt_protocol,wss://ndt_protocol \
```
___
*[`flagx/keyarrayvalue.go` line 38 at r2](https://reviewable.io/reviews/m-lab/go/145#-N49IaDu-uMq6wunoOCB:-N49IaDu-uMq6wunoOCC:b-60at1) ([raw file](https://github.com/m-lab/go/blob/11823785b2027dedb5860fee96510be6f62f9ae9/flagx/keyarrayvalue.go#L38)):*
> ```Go
> 	for k, v := range kav.pairs {
> 		joined := strings.Join(v, ",")
> 		sb.WriteString(fmt.Sprintf("%s:[%s],", k, joined))
> ```

A nice behavior is to make the `String()` method reconstruct the same format that would be accepted on the command line.
___
*[`flagx/keyarrayvalue.go` line 49 at r2](https://reviewable.io/reviews/m-lab/go/145#-N49IugP8pan2CYPoghD:-N49IugP8pan2CYPoghE:bl3hwec) ([raw file](https://github.com/m-lab/go/blob/11823785b2027dedb5860fee96510be6f62f9ae9/flagx/keyarrayvalue.go#L49)):*
> ```Go
> 	h := make(map[string][]string)
> 	for k, s := range kav.pairs {
> 		h[k] = s
> ```

`s` is a pointer and not a copy.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/go/145)* status: 0 of 1 LGTMs obtained

___
*[`flagx/keyarrayvalue.go` line 8 at r2](https://reviewable.io/reviews/m-lab/go/145#-N49Ghms4BASU2vCwL73:-N4D923n9tcDKXQmG3tI:bsmuufg) ([raw file](https://github.com/m-lab/go/blob/11823785b2027dedb5860fee96510be6f62f9ae9/flagx/keyarrayvalue.go#L8)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

All current `*Array` types use "Array" as a suffix. https://pkg.go.dev/github.com/m-lab/go@v0.1.47/flagx

Please rename to `KeyValueArray` -- this will also sort the types naturally together with `KeyValue`. 
</blockquote></details>

When I first wrote it, I spent like 20mins debating whether it should be `KeyValueArray` or `KeyArrayValue`. Ultimately, I saw that in the other `*Array` types, the flag itself is an array (e.g., `StringArray []string`), whereas here, only the value is an array (i.e., `map[string][]string` vs. `[]map[string]string`), so I thought it made sense for the suffix to be `ArrayValue`.

Anyway, I have changed it now.
___
*[`flagx/keyarrayvalue.go` line 28 at r2](https://reviewable.io/reviews/m-lab/go/145#-N49HCVS2oEbZ3jiFy7F:-N4DBE8B8J6B4EwwjoUk:bjtixwu) ([raw file](https://github.com/m-lab/go/blob/11823785b2027dedb5860fee96510be6f62f9ae9/flagx/keyarrayvalue.go#L28)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Hmm...

The other *Array types use append semantics, and allow repeated flags that append the new values to the existing array...

I think this behavior can be preserved here using go's `append`.

These semantics would also mean that we could split `-service=` declarations over multiple lines for clarity, e.g.:

```
-services=ndt/ndt7=ws://ndt/v7/upload,ws://ndt/v7/download \
-services=ndt/ndt7=wss://ndt/v7/upload,wss://ndt/v7/download \
-services=ndt/ndt5=ws://ndt_protocol,wss://ndt_protocol \
```
</blockquote></details>

The `KeyValue` type overwrites the flag instead of appending, so I thought I'd be consistent with that.

Changed.
___
*[`flagx/keyarrayvalue.go` line 38 at r2](https://reviewable.io/reviews/m-lab/go/145#-N49IaDu-uMq6wunoOCB:-N4DIGhxBxuwr7p0PtKh:b-duxycc) ([raw file](https://github.com/m-lab/go/blob/11823785b2027dedb5860fee96510be6f62f9ae9/flagx/keyarrayvalue.go#L38)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

A nice behavior is to make the `String()` method reconstruct the same format that would be accepted on the command line.
</blockquote></details>

I thought about that. That would be something like `key1=value1,value1.1,key2=value2,value2.1,value2.2,key3=value3`. I think, comparatively, `key1:[value1,value1.1],key2:[value2,value2.1,value2.2],key3:[value3]` is more clear, unless there is a cleaner way to separate the `key-[]value` pairs from each other. I thought about using "|" or ";" but I didn't think it looked much better than how it is now.
___
*[`flagx/keyarrayvalue.go` line 49 at r2](https://reviewable.io/reviews/m-lab/go/145#-N49IugP8pan2CYPoghD:-N4DJIyH4E03qOiVNa-H:b-y7igm5) ([raw file](https://github.com/m-lab/go/blob/11823785b2027dedb5860fee96510be6f62f9ae9/flagx/keyarrayvalue.go#L49)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`s` is a pointer and not a copy.
</blockquote></details>

Good catch. I have copied it now.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
One more request. Otherwise this looks good.

> *[Reviewable](https://reviewable.io/reviews/m-lab/go/145#-:-N4DNatt5B559C0MUb3e:bwmtrgk)* status: 0 of 1 LGTMs obtained

___
*[`flagx/keyarrayvalue.go` line 8 at r2](https://reviewable.io/reviews/m-lab/go/145#-N49Ghms4BASU2vCwL73:-N4DK4Bi1QgEnW64B8vM:b-j3a7hu) ([raw file](https://github.com/m-lab/go/blob/11823785b2027dedb5860fee96510be6f62f9ae9/flagx/keyarrayvalue.go#L8)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

When I first wrote it, I spent like 20mins debating whether it should be `KeyValueArray` or `KeyArrayValue`. Ultimately, I saw that in the other `*Array` types, the flag itself is an array (e.g., `StringArray []string`), whereas here, only the value is an array (i.e., `map[string][]string` vs. `[]map[string]string`), so I thought it made sense for the suffix to be `ArrayValue`.

Anyway, I have changed it now.
</blockquote></details>

Aah, I see -- you're right that there is ambiguity. (KeyValue)Array vs Key(ArrayValue) or Key(ValueArray).  Thank you for the name change.
___
*[`flagx/keyarrayvalue.go` line 28 at r2](https://reviewable.io/reviews/m-lab/go/145#-N49HCVS2oEbZ3jiFy7F:-N4DKykFDp8XH5H6EUJs:bnxjzgc) ([raw file](https://github.com/m-lab/go/blob/11823785b2027dedb5860fee96510be6f62f9ae9/flagx/keyarrayvalue.go#L28)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

The `KeyValue` type overwrites the flag instead of appending, so I thought I'd be consistent with that.

Changed.
</blockquote></details>

Ah, I see again. I think we're both making reasonable decisions but based on emphasis on different parts. Here I was emphasizing the "Array" part (where I imagined append makes more sense (it's how the other Array types behave)), and iiuc, you were emphasizing the "Key" part (where you imagined that replacement makes more sense (it's how the KeyValue type behaves))...
___
*[`flagx/keyarrayvalue.go` line 38 at r2](https://reviewable.io/reviews/m-lab/go/145#-N49IaDu-uMq6wunoOCB:-N4DLzfJ8WB2Gmb9Rvx9:b-uglcge) ([raw file](https://github.com/m-lab/go/blob/11823785b2027dedb5860fee96510be6f62f9ae9/flagx/keyarrayvalue.go#L38)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

I thought about that. That would be something like `key1=value1,value1.1,key2=value2,value2.1,value2.2,key3=value3`. I think, comparatively, `key1:[value1,value1.1],key2:[value2,value2.1,value2.2],key3:[value3]` is more clear, unless there is a cleaner way to separate the `key-[]value` pairs from each other. I thought about using "|" or ";" but I didn't think it looked much better than how it is now.
</blockquote></details>

Ah, I see. Yeah, that's harder in this case. Carry on :)
___
*[`flagx/keyvaluearray.go` line 20 at r3](https://reviewable.io/reviews/m-lab/go/145#-N4DMjmd9pLkZ-d-OWpw:-N4DMjmd9pLkZ-d-OWpx:b-i58vek) ([raw file](https://github.com/m-lab/go/blob/fcaafb1405382fe9bac42f95716eeb6c4b2e9c1f/flagx/keyvaluearray.go#L20)):*
> ```Go
> // pair can be specified per call.
> func (kva *KeyValueArray) Set(pair string) error {
> 	p := strings.Split(pair, "=")
> ```

Using `strings.SplitN` allows the value to include an equal sign. https://github.com/m-lab/go/blob/v0.1.47/flagx/keyvalue.go#L28

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/go/145)* status: 0 of 1 LGTMs obtained

___
*[`flagx/keyvaluearray.go` line 20 at r3](https://reviewable.io/reviews/m-lab/go/145#-N4DMjmd9pLkZ-d-OWpw:-N4DviXX-jp6i9t_4EOh:b-wme84n) ([raw file](https://github.com/m-lab/go/blob/fcaafb1405382fe9bac42f95716eeb6c4b2e9c1f/flagx/keyvaluearray.go#L20)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Using `strings.SplitN` allows the value to include an equal sign. https://github.com/m-lab/go/blob/v0.1.47/flagx/keyvalue.go#L28
</blockquote></details>

:thumbsup: done.

**Pull request merged**
