### PR TITLE
Adds new output format for sites/site-machines.json

### PR DESCRIPTION
**Pull request by nkinkade**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/go/146)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
Is it possible to add a unit test like we have for the other formats?

> *[Reviewable](https://reviewable.io/reviews/m-lab/go/146#-:-N5ao0Xr9CzRCno3Et6n:b8epapq)* status: 0 of 1 LGTMs obtained

**Review by nkinkade — COMMENTED** [review]
@cristinaleonr: It is! And I have. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/go/146#-:-N5auGol0Q1cIErnWcix:b-iyp744)* status: 0 of 1 LGTMs obtained

**Review by cristinaleonr — APPROVED** [review]
One more comment.
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/go/146#-:-N5az1aq6La0lvpcUgbG:b6uvllx)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[`siteinfo/client_test.go` line 285 at r4](https://reviewable.io/reviews/m-lab/go/146#-N5ayZfx4srE7EKj3x_d:-N5ayZfx4srE7EKj3x_e:b-3j3eip) ([raw file](https://github.com/m-lab/go/blob/03f3fc28a4bfde944bcab632f92e871936450d32/siteinfo/client_test.go#L285)):*
> ```Go
> 	_, err = client.SiteMachines()
> 	if err != nil {
> 		t.Error("SiteMachines(): expected success, got error.")
> ```

This is the one place we don't use `Errorf`, but it might be useful to add `err` to the error string.

Also, opposite nit: https://github.com/golang/go/wiki/CodeReviewComments#error-strings

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/go/146)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[`siteinfo/client_test.go` line 285 at r4](https://reviewable.io/reviews/m-lab/go/146#-N5ayZfx4srE7EKj3x_d:-N5azIuJ0tdpkfBiM_y3:becjzsi) ([raw file](https://github.com/m-lab/go/blob/03f3fc28a4bfde944bcab632f92e871936450d32/siteinfo/client_test.go#L285)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

This is the one place we don't use `Errorf`, but it might be useful to add `err` to the error string.

Also, opposite nit: https://github.com/golang/go/wiki/CodeReviewComments#error-strings
</blockquote></details>

Actually I just saw the nit does not apply to print statements :). Feel free to ignore.

**Pull request merged**
