### PR TITLE
More bigquery Dataset extensions for dedupping

### PR DESCRIPTION
**Pull request by gfr10598**
Adds DestinationQuery() and Dedup()

This was previously reviewed as https://github.com/m-lab/etl/pull/360, but based on feedback decided to move it to the m-lab/go repo.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/go/10)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
I'm wondering if Dedup is generic enough to warrant including in the m-lab/go packages?

---

Reviewed 1 of 1 files at r4.
Review status: 1 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[bqext/dataset.go, line 166 at r5](https://reviewable.io:443/reviews/m-lab/go/10#-L0GYc2rOHBV54oDxgXK:-L0GYc2rOHBV54oDxgXL:b5g189a) ([raw file](https://github.com/m-lab/go/blob/a7bc47412d2dd45028f16773a7e6299218857b2e/bqext/dataset.go#L166)):*
> ```Go
> ///////////////////////////////////////////////////////////////////
> 
> // TODO - really should take the one that was parsed last, instead
> ```

If de-duplication depends on ordering of specific column names, such as "parse_time" does this belong in a generic package? Or, could this template be a parameter to Dedup?

---

*[bqext/dataset.go, line 192 at r5](https://reviewable.io:443/reviews/m-lab/go/10#-L0Ggk1A_WDWeqpAoG53:-L0Ggk1BDG1ZYxUN8FqI:b-aqemzi) ([raw file](https://github.com/m-lab/go/blob/a7bc47412d2dd45028f16773a7e6299218857b2e/bqext/dataset.go#L192)):*
> ```Go
> 	q := dsExt.DestinationQuery(queryString, dest.Table(table))
> 	if overwrite {
> 		q.QueryConfig.WriteDisposition = bigquery.WriteTruncate
> ```

Could write disposition be a parameter to `DestinationQuery`? The thinking being to possibly encapsulate more of the details of QueryConfig.

---

*[bqext/dataset_integration_test.go, line 87 at r5](https://reviewable.io:443/reviews/m-lab/go/10#-L0G_wKg9EmtXDkTBXhj:-L0G_wKg9EmtXDkTBXhk:b-tppwnk) ([raw file](https://github.com/m-lab/go/blob/a7bc47412d2dd45028f16773a7e6299218857b2e/bqext/dataset_integration_test.go#L87)):*
> ```Go
> // Note that a similar struct is defined in dataset.go, but this
> // one is used for testing the QueryAndParse method.
> type PartitionInfo struct {
> ```

Since this is only a local test dependency, can we call this type something else to prevent confusion? Should the type name be uncapitalized?

Or could we use `bqext.PartitionInfo` safely in the tests instead?

---

*[bqext/dataset_integration_test.go, line 140 at r5](https://reviewable.io:443/reviews/m-lab/go/10#-L0Gb1MH3RPsKBLsVK-d:-L0Gb1MH3RPsKBLsVK-e:b-mbd1p7) ([raw file](https://github.com/m-lab/go/blob/a7bc47412d2dd45028f16773a7e6299218857b2e/bqext/dataset_integration_test.go#L140)):*
> ```Go
> }
> 
> func ClientOpts() []option.ClientOption {
> ```

`clientOpts`?

---

*[bqext/dataset_integration_test.go, line 143 at r5](https://reviewable.io:443/reviews/m-lab/go/10#-L0Gb807TQ80fRbGbHZ_:-L0Gb807TQ80fRbGbHZa:bgfk1nz) ([raw file](https://github.com/m-lab/go/blob/a7bc47412d2dd45028f16773a7e6299218857b2e/bqext/dataset_integration_test.go#L143)):*
> ```Go
> 	opts := []option.ClientOption{}
> 	if os.Getenv("TRAVIS") != "" {
> 		authOpt := option.WithCredentialsFile("../travis-testing.key")
> ```

This relative path could become fragile. At run time could we set an env variable to the location and check for that variable and use the location here?

e.g. `TRAVIS_CREDENTIALS_FILE`?

---

*[bqext/dataset_integration_test.go, line 158 at r5](https://reviewable.io:443/reviews/m-lab/go/10#-L0GbsOEdf4U5PsYuRDI:-L0GbsOEdf4U5PsYuRDJ:b-wzg3rp) ([raw file](https://github.com/m-lab/go/blob/a7bc47412d2dd45028f16773a7e6299218857b2e/bqext/dataset_integration_test.go#L158)):*
> ```Go
> 
> 	// First check that source table has expected number of rows.
> 	// TestDedupSrc should have 6 rows, of which 4 should be unique.
> ```

This test is very dependent on the state of an external project. This could discourage third-parties from considering adopting this for themselves.

Since this is a live test anyway, what if this test constructed the 6-row table that would be du-duped by the rest of the test? This would make the setup self-contained in code. And, it would be possible to re-target the test with a single line change. I could even imagine reading an environment variable for the project name.

---

*[bqext/dataset_test.go, line 136 at r5](https://reviewable.io:443/reviews/m-lab/go/10#-L0Gfgi4yaJdC5uBf1Uy:-L0Gfgi4yaJdC5uBf1Uz:byxz72j) ([raw file](https://github.com/m-lab/go/blob/a7bc47412d2dd45028f16773a7e6299218857b2e/bqext/dataset_test.go#L136)):*
> ```Go
> func TestDestinationQuery(t *testing.T) {
> 	// Create a dummy client.
> 	client := cloudtest.NewChannelClient(make(chan *http.Response, 10))
> ```

Does this need a channel client? Can this use an 'ok client'? I don't see any pre-defined responses.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/go/10#-:-L0Ghjq5Ts7gszFmKtFI:b3wb92i)*

**Comment by gfr10598** [comment]
Review status: 1 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[bqext/dataset.go, line 166 at r5](https://reviewable.io:443/reviews/m-lab/go/10#-L0GYc2rOHBV54oDxgXK:-L0H77b7n10E0FwZ9z2o:bdj8fu0) ([raw file](https://github.com/m-lab/go/blob/a7bc47412d2dd45028f16773a7e6299218857b2e/bqext/dataset.go#L166)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If de-duplication depends on ordering of specific column names, such as "parse_time" does this belong in a generic package? Or, could this template be a parameter to Dedup?
</blockquote></details>

It does not depend on column ordering.  It only will depend on things like parse_time or task_filename in order to perform some sanity checks.  I'd prefer to leave it until later to generalize it.

It definitely could be added as a parameter, so I'll add that now.
Do we want to make it even more general by using some kind of opts... variadic parameter?

---

*[bqext/dataset.go, line 192 at r5](https://reviewable.io:443/reviews/m-lab/go/10#-L0Ggk1A_WDWeqpAoG53:-L0H7qtXnPCvrMvut4Jz:bc2wuhe) ([raw file](https://github.com/m-lab/go/blob/a7bc47412d2dd45028f16773a7e6299218857b2e/bqext/dataset.go#L192)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Could write disposition be a parameter to `DestinationQuery`? The thinking being to possibly encapsulate more of the details of QueryConfig.
</blockquote></details>

Hmm - let me think about that some more.

---

*[bqext/dataset_integration_test.go, line 87 at r5](https://reviewable.io:443/reviews/m-lab/go/10#-L0G_wKg9EmtXDkTBXhj:-L0H5QsRrqd9cZbrzrxK:bu09qnd) ([raw file](https://github.com/m-lab/go/blob/a7bc47412d2dd45028f16773a7e6299218857b2e/bqext/dataset_integration_test.go#L87)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Since this is only a local test dependency, can we call this type something else to prevent confusion? Should the type name be uncapitalized?

Or could we use `bqext.PartitionInfo` safely in the tests instead?
</blockquote></details>

I'm not terribly concerned since this package is bqext_test.  But I'll make it private.

---

*[bqext/dataset_integration_test.go, line 140 at r5](https://reviewable.io:443/reviews/m-lab/go/10#-L0Gb1MH3RPsKBLsVK-d:-L0H68yM8O6TH_i5-H9s:b-896fix) ([raw file](https://github.com/m-lab/go/blob/a7bc47412d2dd45028f16773a7e6299218857b2e/bqext/dataset_integration_test.go#L140)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`clientOpts`?
</blockquote></details>

Done.

---

*[bqext/dataset_integration_test.go, line 143 at r5](https://reviewable.io:443/reviews/m-lab/go/10#-L0Gb807TQ80fRbGbHZ_:-L0H80DR6PdvzNxcoR-6:b1m4izb) ([raw file](https://github.com/m-lab/go/blob/a7bc47412d2dd45028f16773a7e6299218857b2e/bqext/dataset_integration_test.go#L143)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This relative path could become fragile. At run time could we set an env variable to the location and check for that variable and use the location here?

e.g. `TRAVIS_CREDENTIALS_FILE`?
</blockquote></details>

I'll add an issue.  Probably pretty easy to do.
https://github.com/m-lab/go/issues/11

---

*[bqext/dataset_integration_test.go, line 158 at r5](https://reviewable.io:443/reviews/m-lab/go/10#-L0GbsOEdf4U5PsYuRDI:-L0H6bl9dfpVDd6gKCjX:btci608) ([raw file](https://github.com/m-lab/go/blob/a7bc47412d2dd45028f16773a7e6299218857b2e/bqext/dataset_integration_test.go#L158)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This test is very dependent on the state of an external project. This could discourage third-parties from considering adopting this for themselves.

Since this is a live test anyway, what if this test constructed the 6-row table that would be du-duped by the rest of the test? This would make the setup self-contained in code. And, it would be possible to re-target the test with a single line change. I could even imagine reading an environment variable for the project name.
</blockquote></details>

Agree. Already created https://github.com/m-lab/go/issues/8
Added comment.

---

*[bqext/dataset_test.go, line 136 at r5](https://reviewable.io:443/reviews/m-lab/go/10#-L0Gfgi4yaJdC5uBf1Uy:-L0H72xsebKlgGrcOVXb:b-896fix) ([raw file](https://github.com/m-lab/go/blob/a7bc47412d2dd45028f16773a7e6299218857b2e/bqext/dataset_test.go#L136)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does this need a channel client? Can this use an 'ok client'? I don't see any pre-defined responses.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/go/10)*

**Comment by stephen-soltesz** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[bqext/dataset.go, line 166 at r5](https://reviewable.io:443/reviews/m-lab/go/10#-L0GYc2rOHBV54oDxgXK:-L0H9yMRUWYi6Bq9JVWO:b-e4wj8l) ([raw file](https://github.com/m-lab/go/blob/a7bc47412d2dd45028f16773a7e6299218857b2e/bqext/dataset.go#L166)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

It does not depend on column ordering.  It only will depend on things like parse_time or task_filename in order to perform some sanity checks.  I'd prefer to leave it until later to generalize it.

It definitely could be added as a parameter, so I'll add that now.
Do we want to make it even more general by using some kind of opts... variadic parameter?

</blockquote></details>

By ordering I meant as-in "parsed last". 

When I was reading this earlier, I think I was trying to imagine whether Dedup would be plausibly useful to a third-party. But, that may be too broad a criteria. If I imagine the goal for m-lab/go being to add generally useful routines that we may use across our own repos, then that's easier.

Something still feels funny. If I ran Dedup twice on the same source, would I get the same result? Are there any other implicit dependencies between the input table and the implementation of Dedup?

If dedupTemplate was a parameter, perhaps the functionality of Dedup becomes immediately more generic. The operation becomes something like `Filter` or `Record` or something -- taking data from a query and writing it to a new table, "dedup" being one application of it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/go/10)*

**Comment by gfr10598** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[bqext/dataset.go, line 166 at r5](https://reviewable.io:443/reviews/m-lab/go/10#-L0GYc2rOHBV54oDxgXK:-L0KWZrdK8BALdFd0k7h:b86mod) ([raw file](https://github.com/m-lab/go/blob/a7bc47412d2dd45028f16773a7e6299218857b2e/bqext/dataset.go#L166)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

By ordering I meant as-in "parsed last". 

When I was reading this earlier, I think I was trying to imagine whether Dedup would be plausibly useful to a third-party. But, that may be too broad a criteria. If I imagine the goal for m-lab/go being to add generally useful routines that we may use across our own repos, then that's easier.

Something still feels funny. If I ran Dedup twice on the same source, would I get the same result? Are there any other implicit dependencies between the input table and the implementation of Dedup?

If dedupTemplate was a parameter, perhaps the functionality of Dedup becomes immediately more generic. The operation becomes something like `Filter` or `Record` or something -- taking data from a query and writing it to a new table, "dedup" being one application of it.

</blockquote></details>

I'm definitely using the "useful to other repos in m-lab" criteria.  Irene might use this, except she isn't using Go.  8-(

Yes if you run Dedup twice you should get the same result.  I do not believe there are any other implicit dependencies.

I kinda like the idea of making this a Filter method, but I don't like the idea of injecting an arbitrary query.  Then it starts to look like DestinationQuery, I think.

I could, however, extract the bottom bit of the code into a generic ExecQuery or something like that, for queries with not output expected.  Let me try that out and you can see what you think.

With this extraction, I'd also be content moving the Dedup method itself back to the etl cmd/dedup package.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/go/10)*

**Comment by gfr10598** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[bqext/dataset.go, line 192 at r5](https://reviewable.io:443/reviews/m-lab/go/10#-L0Ggk1A_WDWeqpAoG53:-L0Ka4tZlYemcDeYs3XL:bbby6wu) ([raw file](https://github.com/m-lab/go/blob/a7bc47412d2dd45028f16773a7e6299218857b2e/bqext/dataset.go#L192)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Hmm - let me think about that some more.
</blockquote></details>

I think it should be and will add that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/go/10)*

**Comment by stephen-soltesz** [comment]
Review status: 1 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[bqext/dataset.go, line 166 at r5](https://reviewable.io:443/reviews/m-lab/go/10#-L0GYc2rOHBV54oDxgXK:-L0LU1K1MDnnWH84Lt1A:b-l39y02) ([raw file](https://github.com/m-lab/go/blob/a7bc47412d2dd45028f16773a7e6299218857b2e/bqext/dataset.go#L166)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I'm definitely using the "useful to other repos in m-lab" criteria.  Irene might use this, except she isn't using Go.  8-(

Yes if you run Dedup twice you should get the same result.  I do not believe there are any other implicit dependencies.

I kinda like the idea of making this a Filter method, but I don't like the idea of injecting an arbitrary query.  Then it starts to look like DestinationQuery, I think.

I could, however, extract the bottom bit of the code into a generic ExecQuery or something like that, for queries with not output expected.  Let me try that out and you can see what you think.

With this extraction, I'd also be content moving the Dedup method itself back to the etl cmd/dedup package.



</blockquote></details>

I like the separation between "exec query" and "dedup" now.

---

*[bqext/dataset.go, line 165 at r9](https://reviewable.io:443/reviews/m-lab/go/10#-L0LFAxOyA6g12GpuDe0:-L0LFAxOyA6g12GpuDe1:b-m9zh6g) ([raw file](https://github.com/m-lab/go/blob/e9b7a3c717264bf91e28d51fabb6cc5198e52b25/bqext/dataset.go#L165)):*
> ```Go
> 
> // ExecDestQuery constructs a destination query, executes it, and returns status or error.
> func (dsExt *Dataset) ExecDestQuery(query string, disposition bigquery.TableWriteDisposition, destTable *bigquery.Table) (*bigquery.JobStatus, error) {
> ```

nit: I would advocate for symmetry across names like `DestinationQuery` and `ExecDestQuery`. i.e. either both use the full name or both use the short names. 

---

*[bqext/dataset.go, line 165 at r9](https://reviewable.io:443/reviews/m-lab/go/10#-L0LI5DLbpDSM0bGHpV4:-L0LI5DLbpDSM0bGHpV5:bxiohey) ([raw file](https://github.com/m-lab/go/blob/e9b7a3c717264bf91e28d51fabb6cc5198e52b25/bqext/dataset.go#L165)):*
> ```Go
> 
> // ExecDestQuery constructs a destination query, executes it, and returns status or error.
> func (dsExt *Dataset) ExecDestQuery(query string, disposition bigquery.TableWriteDisposition, destTable *bigquery.Table) (*bigquery.JobStatus, error) {
> ```

`destTable` is a much better parameter than the three project/dataset/table parameters before. :+1:

---

*[bqext/dataset.go, line 165 at r9](https://reviewable.io:443/reviews/m-lab/go/10#-L0LTxIu3dYGOUJq0NdU:-L0LTxIu3dYGOUJq0NdV:b-taf4q2) ([raw file](https://github.com/m-lab/go/blob/e9b7a3c717264bf91e28d51fabb6cc5198e52b25/bqext/dataset.go#L165)):*
> ```Go
> 
> // ExecDestQuery constructs a destination query, executes it, and returns status or error.
> func (dsExt *Dataset) ExecDestQuery(query string, disposition bigquery.TableWriteDisposition, destTable *bigquery.Table) (*bigquery.JobStatus, error) {
> ```

ExecDestQuery sounds like it executes a value returned by DestinationQuery. Is that possible?  Running and Waiting for a query seems like a generally useful pattern.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/go/10)*

**Comment by gfr10598** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[bqext/dataset.go, line 165 at r9](https://reviewable.io:443/reviews/m-lab/go/10#-L0LFAxOyA6g12GpuDe0:-L0LacmwOe5rE1GEWbgA:b-896fix) ([raw file](https://github.com/m-lab/go/blob/e9b7a3c717264bf91e28d51fabb6cc5198e52b25/bqext/dataset.go#L165)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: I would advocate for symmetry across names like `DestinationQuery` and `ExecDestQuery`. i.e. either both use the full name or both use the short names. 
</blockquote></details>

Done.

---

*[bqext/dataset.go, line 165 at r9](https://reviewable.io:443/reviews/m-lab/go/10#-L0LTxIu3dYGOUJq0NdU:-L0Ladn3fNCqdJn5pthv:b-896fix) ([raw file](https://github.com/m-lab/go/blob/e9b7a3c717264bf91e28d51fabb6cc5198e52b25/bqext/dataset.go#L165)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

ExecDestQuery sounds like it executes a value returned by DestinationQuery. Is that possible?  Running and Waiting for a query seems like a generally useful pattern.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/go/10)*

**Comment by gfr10598** [comment]
PTAL.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/go/10#-:-L0LalVvb9wZeTFrE011:b-83330m)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[bqext/dataset.go, line 144 at r10](https://reviewable.io:443/reviews/m-lab/go/10#-L0Lb1EOKfpU9Trz0XW9:-L0Lb1EPVJtvthwVFMUr:bgsxz1) ([raw file](https://github.com/m-lab/go/blob/a8f36049b3dd900d1b336783641bbf048fc252f5/bqext/dataset.go#L144)):*
> ```Go
> }
> 
> // DestinationQuery constructs a query with common Config settings for
> ```

s/DestinationQuery/DestQuery/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/go/10#-:-L0Lbij-lVOCjj3_q7W2:bnfp4nl)*

**Pull request merged**
